### ISSUE TITLE
2つ目の爆弾のコードについて

### ISSUE THREAD

**Issue by c0b21059c5** [c0b21007/ProjexD#7]
https://github.com/c0b21007/ProjexD/blob/bfdb00d11d0f3eeabfe3a827a36ac42fa0b9167b/Ex04/dodge_bomb.py#L39
同じ文を2つ書くならfor文を利用したほうがいいと思いました

**Comment by c0b21007** [comment]
試したのですが、うまくできませんでした。
次までに勉強しておきます
